### ISSUE TITLE
Automatically add a person as a collaborator after their first merged PR

### ISSUE THREAD

**Issue by wokalski** [reason-react-native/reason-react-native#196]
This has been the policy in this repo from the beginning and it'd be nice to formalise it and automate it.

**Comment by MoOx** [comment]
Really interested by the tooling for this 👌

**Comment by wokalski** [comment]
@MoOx maybe Danger or Peril could help with this. cc @orta

**Comment by orta** [comment]
It could, [Moya does this with Aeryn](https://github.com/Moya/moya-peril#what-is-this-project)

**Comment by wokalski** [comment]
Thanks @orta. Very appreciated!

**Comment by grabbou** [comment]
We could also add few additional notices, like where we are hanging out on Discord to discuss details so that people can get involved in the direction where we are going.

This might be useful so that merging happens always given the context of current development.

Anyone has some battle-tested documents here?

**Comment by MoOx** [comment]
There is not enough contribution that justify working on that imo. We can still revisit this later in time.
