### ISSUE TITLE
Support bs-platform@7

### ISSUE THREAD

**Issue by idkjs** [reason-react-native/reason-react-native#629]
## The problem

Is `bs-platform@7.0.1` on the roadmap?

## Considered solution

I started the conversion here: https://github.com/idkjs/reason-react-native/tree/bs_platform_701

Tested on the template here: https://github.com/idkjs/reason-react-native-bs701

Of note, I have not completed [VirtualizedList.re](https://github.com/idkjs/reason-react-native/blob/bs_platform_701/src/components/VirtualizedSectionList.re) yet since there is some trickery with `section` in that file. 

I also have not converted the `.md`'s yet. I wanted to get some feedback before continuing. 

All of the changes are to implement the new syntax. A few examples are:

![registry](https://user-images.githubusercontent.com/2370391/70565401-08ff9780-1b60-11ea-9cf1-e54f7530e0c7.jpg)
![photoIdentifier](https://user-images.githubusercontent.com/2370391/70565402-08ff9780-1b60-11ea-9c64-3b8932c81f26.jpg)
![layoutEvent](https://user-images.githubusercontent.com/2370391/70565403-08ff9780-1b60-11ea-9324-ba25494ff5f1.jpg)

How do you test this repo? Is there a way to find out if I have broken anything?

Should I make a pull request?

**Comment by MoOx** [comment]
Yeah sure bs 7 should be handled :) On all repos!

That said, this will be a breaking change release, a huge one.
We shouldn't probably rush on releasing that, as most people won't be ready to upgrade all there projects. Not sure if we can easily provide a upgrade script (most of the changes will be "## => ." but how to know what is RN & what is normal "js/json" from the user?)

For now the best way to test is to use unreleased branch in real world projects.
We could do an app + auto testing (via detox) but to cover entire react native apis, that will be a lot of work & a lot of maintenance... :) 

@cknitt @sgny any idea/comment on how to handle such a breaking change?

**Comment by sgny** [comment]
We already have a fairly complete release that does not seem to have any major issues at the moment., if any such issues arise, we can make a branch of the repo before the breaking changes, so that users on v5 and v6 do not have to immediately move to v7.

I think not having to deal with `Js.t` objects is a huge QOL improvement and in comparison the move to v7 itself is quite painless and can be dealt with a simple script as you said. We can add a disclaimer that If users had their own `Js.t` objects, they will break, so that there is no surprise when the compiler throws that error.

**Comment by MoOx** [comment]
I guess we could do a branch & keep maybe 2 version aside for a while until bs 7 is commonly used. like `reason-react-native@0.61`& reason-react-native@0.61-bs7` something like that.

Indeed I didn't think about a script that just totally remove Js.t() for good :D

**Comment by idkjs** [comment]
I agree with you all. bsp7 is huge. Simplifies things a whole lot and we should support it as soon as possible because every single time someone runs `npm -D bs-platform` they will be getting version 7. And presumably writing code in the style of bsp7. I don't mind testing it. Can we suggest any good, fairly complex examples out there that I could install 7 on and see what happens? I was going to try on @cem2ran's https://github.com/cem2ran/InstaClone but I could not get it run properly.

**Comment by sgny** [comment]
I'm going to backtrack a little.

@idkjs Since `Js.t` objects seem to work without issues with v7 (in my limited testing), there shouldn't be any issues with users transitioning to v7 even now. I'm not aware of that syntax getting deprecated or removed on any schedule, but I may be mistaken., so please correct me if I have missed the notice.

On the other hand, even though I don't much like `Js.t` objects, I should avoid being biased. Having to use the `##` accessor, as is our convention, does remind one that one is dealing with an external object. That could justify keeping them.

While we are discussing these changes, we should also consider object creation. As BS records are JS objects now, do we want to keep constructors defined with the `bs.obj` decorator? Again, the current convention seems to work quite alright and could be kept.

TBH, the tangible benefit I'm aware of is the cleaner output when we have submodules and functors. We could take advantage of that even now.

**Comment by idkjs** [comment]
> Since Js.t objects seem to work without issues with v7 (in my limited testing), there shouldn't be any issues with users transitioning to v7 even now. I'm not aware of that syntax getting deprecated or removed on any schedule, but I may be mistaken., so please correct me if I have missed the notice.

Probably not getting deprecated. If you start using the new syntax, you will be accessing you keys with `.` to access your `js` objects. In my experience running through this and other repos, I did find myself having to think about whether an entity was a proper reason record or some value that came from `js` since we are accessing both with `.`. Compiler will keep you inline though. It's better than ever. The reminder point is a good one. Worth noting that since most of the code is behind an `.rie`, the end use shouldn't see any changes, right? I am asking. I don't have enough experience. I know that when I toss the bs7 version into an old reason-react-native project, it runs, whatever that means.

> While we are discussing these changes, we should also consider object creation. As BS records are JS objects now, do we want to keep constructors defined with the bs.obj decorator? Again, the current convention seems to work quite alright and could be kept.

In the [`bs_platform_701`](https://github.com/idkjs/reason-react-native/tree/bs_platform_701) branch I changed every `[@bs.obj]` that didn't have a `[@bs.string]` special type into a reason object as `bs.string` variants aren't supported in the new syntax. So mixing them doesn't hurt and the files are cleaner. Just for fun, though, I might go try turning some into [inline values modules](https://dev.to/yawaramin/inlined-values-in-bucklescript-247c) though, if @yawaramin says its not zero-cost.

> TBH, the tangible benefit I'm aware of is the cleaner output when we have submodules and functors. We could take advantage of that even now.

If you show me an example of this, I will go do it.

At any rate, I do not need this to happen for any reason. I thought maybe it would be a thing we wanted to do and it I learned a whole lot going over your code line by line. So, If there is no interest we can go ahead and close this issue.

**Comment by sgny** [comment]
> > Since Js.t objects seem to work without issues with v7 (in my limited testing), there shouldn't be any issues with users transitioning to v7 even now. I'm not aware of that syntax getting deprecated or removed on any schedule, but I may be mistaken., so please correct me if I have missed the notice.
> 
> Probably not getting deprecated. If you start using the new syntax, you will be accessing you keys with `.` to access your `js` objects. In my experience running through this and other repos, I did find myself having to think about whether an entity was a proper reason record or some value that came from `js` since we are accessing both with `.`. Compiler will keep you inline though. It's better than ever. The reminder point is a good one. Worth noting that since most of the code is behind an `.rei`, the end user shouldn't see any changes, right? I am asking. I don't have enough experience. I know that when I toss the bs7 version into an old reason-react-native project, it runs, whatever that means.

Even for components without interface files, very little would need to change. We would not need to change names of any types (in case anyone else types everything explicitly like I do!). What would matter are the valid keys. As you observed, once a type is redefined as a BS record, then the compiler will enforce the `.` accessor (and the `##` accessor if the type remains `Js.t`). Basically, at least for the replacement of `Js.t` types with BS records, the users would only need to replace `##` with `.`.

> 
> > While we are discussing these changes, we should also consider object creation. As BS records are JS objects now, do we want to keep constructors defined with the bs.obj decorator? Again, the current convention seems to work quite alright and could be kept.
> 
> In the [`bs_platform_701`](https://github.com/idkjs/reason-react-native/tree/bs_platform_701) branch I changed every `[@bs.obj]` that didn't have a `[@bs.string]` special type into a reason object as `bs.string` variants aren't supported in the new syntax. So mixing them doesn't hurt and the files are cleaner. Just for fun, though, I might go try turning some into [inline values modules](https://dev.to/yawaramin/inlined-values-in-bucklescript-247c) though, if @yawaramin says its not zero-cost.
> 

Actually, he says the cost is incurred only when used. For example, the `decelerationRate` prop for the `ReactNativeWebView` bindings accepts floats or string literals, so I used (after @cknitt with the version in this repo) `bs.inline` for the string literals and a function to cast floats as the appropriate type. When you pass such a value to this prop as below 

```reason
decelerationRate=ReactNativeWebView.DecelerationRate.fast
```

the output is simply

```js
decelerationRate: "fast",
```
So there is no additional cost.

We usually have to resort to `bs.inline` for string literals with `Js.t` objects passed to callback functions (so the above is an exception). They are verbose and we also have to define interfaces for them to prevent arbitrary new values to be created, etc. They also would have to be either defined multiple times for when the sets of allowed values are not quite the same. so we would have to have different scopes, etc.

The clear advantage with polymorphic variants is that they are identical no matter where you use them, you do not have to have them in scope. I think that matches very well with string literals. We cannot define a type made up of polymorphic variants, but we probably could not reuse them in practice anyway. Greatest opportunity for reuse would probably be with `Style` props, and there the sets of aligned values are not identical so we'd have to define multiple types.

> > TBH, the tangible benefit I'm aware of is the cleaner output when we have submodules and functors. We could take advantage of that even now.
> 
> If you show me an example of this, I will go do it.
> 

Nothing is needed, the output is nicer with v7 for the same syntax.  With v7, `Animated.bs.js` has 

```js
var Value = {
  Decay: Decay,
  Spring: Spring,
  Timing: Timing,
  interpolate: interpolate
};
```

instead of

```js
var Value = /* module */[
  /* Decay */Decay,
  /* Spring */Spring,
  /* Timing */Timing,
  /* interpolate */interpolate
];
```

The latter is easier to read and closer to JS code written by a human. 

> At any rate, I do not need this to happen for any reason. I thought maybe it would be a thing we wanted to do and it I learned a whole lot going over your code line by line. So, If there is no interest we can go ahead and close this issue. Thank you,sirs, for taking the time to give considered responses.

I do appreciate that you have brought this up and that these design choices are considered. It's just as valid to keep `Js.t` types as to change to BS records; the former allows a useful differentiation, the latter is more idiomatic now. Admittedly, I'm not too keen on `bs.string` for `bs.inline` and would prefer to keep the constructors, but the discussion is still open.

**Comment by MoOx** [comment]
To make this short: I propose we start a branch on this & keep for a few months 2 version of the bindings (should be hard to back port fixes/changes now that we cover most of RN on 2 branches).

I find the `.` compared to `##` clearly better for new comers & the bs7 record thing is especially nice for interop when you want to use Reason code from JS (yeah that can be a thing, which make sense if you integrate reason in a JS app & want to use your new reason component from old js code).

So @idkjs I am adding you to the org so you can create a branch in the repo to directly put things here so we might work on this together as a team :)

**Comment by idkjs** [comment]
Cool. I will get on that. Should we close this?

**Comment by idkjs** [comment]
Ok. First time being added to an org. Again, thank you. I have cloned this repo, created a branch with the branch code, then tried to `git push origin branch-name`. The password is a github token, though I tried with my regular password as well. I get the following error:

```sh
reason-react-native-org [bs-platform-7.0.1]git push origin bs-platform-7.0.1
Username for 'https://github.com': idkjs
Password for 'https://idkjs@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/reason-react-native/reason-react-native.git/'
``` 

Any guidance would be appreciated. Thank you.

**Comment by sgny** [comment]
@idkjs You need to turn on two-factor authentication, if you have not already done so.

**Comment by idkjs** [comment]
Already did that.

**Comment by MoOx** [comment]
We should close this when a release is made, not before :)

The org doesn't change a thing, let me check that the rights are correct.

It seems ok.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/157534/70743553-47dc4b80-1d20-11ea-890e-1586773921b5.png">

You might need to check your git config, maybe setup ssh?

**Comment by idkjs** [comment]
Don't think I have my git ssh setup. Was using the `http` instructions on git. Will get on it. Thank you, sir.

**Comment by idkjs** [comment]
Finally got it to go. New branch is here:https://github.com/reason-react-native/reason-react-native/tree/bs-platform-7.0.1

**Comment by MoOx** [comment]
I opened your branch as a PR so we can track progress :) Thanks for starting this initiative!

**Comment by cknitt** [comment]
I am late to the party. 😉 Not using bs7 yet because of some minor Reason parser issues affecting our codebase that are still being ironed out. Should be good with the next BS release though.

In any case, I would love to have records instead of `Js.t ` objects, too. I left some comments in the PR.
