### ISSUE TITLE
ActivityIndicator size cannot be a numeric value since 0.63

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#732]
See https://github.com/reason-react-native/reason-react-native/pull/724/files#diff-69f1e2e1299d6064a3a4e2bb26d5807f93c86d62fc9935a33f956db782d06ac9

`exact` has been deleted.

@cknitt is this a mistake or was this on purpose (assuming nobody use this for example) ?

**Comment by cknitt** [comment]
@MoOx It seems this was a mistake, sorry!

This means we'll probably need to revert this to an abstract type if we want a clean solution.

**Comment by MoOx** [comment]
Can't we this be enough to add something like 

```reason
external makeSize: float => size = "%identity";
```

**Comment by cknitt** [comment]
As long as the user just passes the value as a prop to the ActivityIndicator component, this will work fine.

But it may cause issues if the user "casts" a float to a size value and processes it in some other way, with the compiler thinking that it is a polymorphic variant.

**Comment by MoOx** [comment]
Can we consider this an edge case enough (who is going to write ActivitiIndicator.exact(8.) and will switch on this? 😂)
Otherwise we can rollback indeed.
@sgny any additional thought ?

**Comment by sgny** [comment]
Thanks for the kind callout. I haven't been able to contribute in the past few months, but you have ensure great progress @MoOx and @cknitt.

Since `@bs.unwrap` still isn't available with labeled arguments, I don't have a clearly better idea at this time. However, as @cknitt pondered, if some `float` value is cast as `size` it can be passed into a function that accepts any type defined identically to `size`. That can potentially raise issues, but can be avoided with some attention. 

An alternative might be to use `@unboxed` as below:
```
type discreteSize = [ | `small | `large ];

[@unboxed]
type size =
  | Size('a): size;
let discrete = (v: discreteSize) => Size(v);
let float = (v: float) => Size(v);
```

That does cause some unnecessary JS artifacts 

```
type size;

external discrete: [ | `small | `large ] => size = "%identity";
external float: float => size = "%identity";
```

In case we simply add a `makeSize` function, the likelihood of misuse is not very high, but above medicine isn't too bitter either. I'll prepare a PR if you'd prefer either instead of reverting to `bs.inline` or adding `makeSize`.

**Comment by sgny** [comment]
Apparently, the compiler does not prevent calling constructors of types defined with the `unboxed` annotation , i.e. as defined above `Size(1)` or `Size(false)` are perfectly valid and will be unboxed as `1` or `false`. Accordingly the `size` type needs to be made abstract and the first version above would therefore need to be revised as:

```
module Size: {
  type discrete = [ | `small | `large ];

  type t;
  let discrete : discrete => t;
  let float : float => t
} = {
  type discrete = [ | `small | `large ];

  [@unboxed]
  type t =
    | Size('a): t;
  let discrete = (v: discrete) => Size(v);
  let float = (v: float) => Size(v);
};
```
or another module needs to be added for the type, which is more inline with the style throughout our repo.

I find the second version more straightforward, significantly so. Indeed, I'm having trouble understanding the use case for `unboxed`.

**Comment by cknitt** [comment]
Instead of

```reason
Size.discrete(`small)
```

I'd prefer to have just `Size.small` like it was before.

I therefore suggest reverting to the previous implementation (that used an abstract type and `%identity`).

**Comment by sgny** [comment]
Sure, these are not better options and indeed more verbose.

**Comment by MoOx** [comment]
I just reverted this and pushed as a breaking change in a patch release (shouldn't be a big deal to adjust, sorry).
